### ISSUE TITLE
Untagged Resources

### ISSUE THREAD

**Issue by cnuss** [cloudgraphdev/cli#3]
Is there a way or is it possible to add a query for untagged resources?

**Comment by tyler-dunkel** [comment]
So you can query a service for all instances that do not have tags like so:

```
query {
  queryawsKms(filter:{not: {has: tags}}) {
    arn
    tags {
      key
    }
  }
}
```

In order to get ALL services that do not have tags, I believe you would currently need to create a query like above for each service. We plan in the future to add a top level list of all services like `queryawsServices` that could support this as a single query but it's not currently on the roadmap.
